DROP DATABASE IF EXISTS db;
CREATE DATABASE db;

CREATE TABLE db.message (
  id  INT PRIMARY KEY AUTO_INCREMENT,
  question  VARCHAR (100) NOT NULL DEFAULT '',
  answer  VARCHAR (100) NOT NULL DEFAULT  ''
);